authentication/urls.py
from django.urls import path
from authentication.views import (
    SignUpView, 
    SignInView,
    SignOutView,
    PRView,
    PRDone,
    PRconfirm,
    PRComplete,
)
urlpatterns  = [
    path('signup', SignUpView.as_view(), name='signup_view'),
    path('signin', SignInView.as_view(), name='signin_view'),
    path('signout', SignOutView.as_view(), name='signout_view'),
    path('password/reset',PRView.as_view(), name='password_reset'),
    path('password/reset/done',PRDone.as_view() , name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>',PRconfirm.as_view() , name='password_reset_confirm'),
    path('password/reset/complete/', PRComplete.as_view(), name='password_reset_complete')
]

core/urls.py
from django.urls import path
from core.views import (
    HomeView,
)
from django.contrib.auth.decorators import login_required
urlpatterns  = [
    path('feed/', (HomeView.as_view()), name='home_feed'),
]

instaclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('core.urls')),
    # path('', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models

# Create your models here.

core/models.py
# from _typeshed import Self
from django.db import models
from django.contrib.auth import get_user_model
from crum import get_current_user
from core.utils import auto_save_current_user

User = get_user_model()

# Create your models here.
#Post Model

class Post(models.Model):
    text = models.CharField(max_length=144, blank=True, null=True)
    image = models.ImageField(upload_to='post_images') #BASE_DIR ->media ->post_images
    users = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    # status = models.ForeignKey(on_delete=models.PROTECT,db_constraint=False)
    def __str__(self):
        return str(self.pk)

    # def save(self, *args, **kwargs):
    #     user = get_current_user()
    #     if not self.id:
        # if user and not user.pk:
        #     user = None
        # if not self.pk:
        #     self.user = user
        # super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Post, self).save(*args, **kwargs)
        # Post.save()

#Comment Model
class Comment(models.Model):
    text = models.CharField(max_length=150)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    users = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    commented_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.pk)

    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs)
#Likes Model
class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    users = models.ForeignKey(User, on_delete=models.CASCADE)
    is_like = models.BooleanField(default=True)
    liked_on =models.DateTimeField(auto_now_add =True)
    created_on = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.is_like)


# followers model
class Follow(models.Model):
    users = models.ForeignKey(User, related_name='follow_user', on_delete=models.CASCADE)
    follower = models.ForeignKey(User, related_name='follow_follower', on_delete= models.CASCADE)
    is_follow = models.BooleanField(default=True)
    followed_on = models.DateTimeField(auto_now_add =True)
    updated_on = models.DateTimeField(auto_now_add =True)

    def __str__(self):
        return f"{self.user} --> {self.follower}"

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from user.managers import CustomUserManager
# Create your models here.

class User(AbstractUser):
    picture = models.ImageField(upload_to='profile_pictures', blank= True, null= True)
    full_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

    first_name = None
    last_name = None

    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name', 'username',]

    objects = CustomUserManager()

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model



class UserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('full_name', 'email', 'username', 'password1', 'password2')



class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('full_name', 'email', 'username',)

authentication/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from authentication.forms import UserForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import (
     PasswordResetView, 
     PasswordResetConfirmView,
     PasswordResetCompleteView,
     PasswordResetDoneView,
)
# Create your views here.

def home(request):
    return HttpResponse('home')
# @login_required
class SignInView(View):
    template_name = 'authentication/signin.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        password = request.POST.get('password')
        try:
            user_obj = User.objects.get(username=email_username)
            email = user_obj.email
        except Exception as e:
            email = email_username
        
        user = authenticate(request, email=email, password=password)
        
        if user is None:
            messages.error(request, 'Invalid Login.', extra_tags="error")
            return render(request, self.template_name)
        
        login(request, user)
        messages.success(request, 'Thanks for Login, Welcome to Insta clone.', extra_tags='success')
        return redirect('home_feed')
        
        # return render(request, self.template_name)


class SignUpView(View):
    template_name = 'authentication/signup.html'
    from_class = UserForm

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        form = self.from_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('signin_view')

        context = {'form': form}

        return render(request, self.template_name, context)
        
class SignOutView(View):
    def post(self, request, *args, **kwargs):
        logout(request)
        return redirect('signin_view')

class PRView(PasswordResetView):
    template_name = 'authentication/password_reset.html'

class PRDone(PasswordResetDoneView):
    template_name = 'authentication/password_reset_done.html'


class PRconfirm(PasswordResetConfirmView):
    template_name = 'authentication/password_reset_confirm.html'

class PRComplete(PasswordResetCompleteView):
    template_name = 'authentication/password_reset_complete.html'

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.
class HomeView(TemplateView):
    template_name = 'core/feed.html'

user/views.py
from django.shortcuts import render

# Create your views here.

templates/authentication/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block extra_head %}{% endblock %}

    <title>Insta Clone</title>
  </head>
  <body>

    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block extra_body %}{% endblock %}

  </body>
</html>

templates/authentication/components/no_login_navbar.html
{% load static %}

<header>
    <nav class="navbar navbar-light bg-white border-bottom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/instalogo.png' %}" class="nav__insta__logo">
            </a>
        </div>
    </nav>
</header>

templates/authentication/password_reset.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

<header>
    <nav class="navbar navbar-light bg-white border-bottom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/instalogo.png' %}" class="nav__insta__logo">
            </a>
        </div>
    </nav>
</header>

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Trouble Signin In?</h4></div>
                    <div class="forgot__password__text py-2">
                        Enter your email, phone, or username and we'll send you a link to get back into your account.
                    </div>
                    <div class="mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email" required maxlength="240" autocomplete="email">
                            </div>
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn">Send Signin Link</button>
                            </div>
                        </form>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_complete.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

{% include 'authentication/components/no_login_navbar.html' %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Successfully Reset</h4></div>
                    <div class="forgot__password__text py-2">
                        You can go ahead and signin now.
                        <br>
                        <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">
                            Click here to Sign In.
                        </a>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_confirm.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

{% include 'authentication/components/no_login_navbar.html' %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Trouble Signin In?</h4></div>
                    <div class="forgot__password__text py-2">
                        Enter your email, phone, or username and we'll send you a link to get back into your account.
                    </div>
                    <div class="mb-3">
                        {% if form %}
                            <div>
                                {% if form.non_field_errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ form.non_field_errors }}
                                    </div>
                                {% endif%}
                            </div>
                            <form method="POST">
                                {% csrf_token %}
                                <div class="my-1 form__input">
                                    <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" placeholder="Password">
                                    <p>{{ form.new_password1.errors }}</p>
                                </div>
                                <div class="my-1 form__input">
                                    <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" placeholder="Retype Password">
                                    <p>{{ form.new_password2.errors }}</p>
                                </div>
                                <div class="my-4 mx-auto text-center">
                                    <button class="btn btn-sm auth__btn">Set Password</button>
                                </div>
                            </form>
                        {% else %}
                            <div class="py-2">
                                <strong style="color: #ff6600;">Your password reset link is invalid or expired.</strong>
                            </div>
                        {% endif %}
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_done.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

{% include 'authentication/components/no_login_navbar.html' %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-4 mb-5">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Email Sent.</h4></div>
                    <div class="forgot__password__text py-2">
                        Check your registered email for the Password Reset link.
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_email.html
Devjunction is trying to steal your pasword- {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/signup.css' %}">
{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto signup__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mt-4 mb-3 mx-auto">
                <div class="signup">
                    <p class="signup__card__text">Sign up to see photos and videos from your friends.</p>
                    <div class="my-4 mx-auto text-center">
                        <button class="btn btn-sm auth__btn">Log in with Facebook</button>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div>
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif%}
                    </div>
                    <div class="signup__form mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email" class="form-control {% if form.email.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.email.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_username" type="text" name="username" placeholder="Username" class="form-control {% if form.username.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.username.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_full_name" type="text" name="full_name" placeholder="Full Name" class="form-control {% if form.full_name.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.full_name.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password1" type="password" name="password1" placeholder="Password" class="form-control {% if form.password1s.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.password1.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password2" type="password" name="password2" placeholder="Retype Password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.password2.errors }}
                                </div>
                            </div>
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn" type="submit">Sign up</button>
                            </div>
                        </form>
                    </div>
                    <p class="terms__conditions mb-4">By signing up, you agree to our <strong>Terms</strong> , <strong>Data Policy</strong> and <strong>Cookies Policy</strong> .</p>
                </div>
            </div>
            <div class="text-center card mt-2 px-5 mx-auto signup__card">
                <p class="have__an__account py-3">Have an account? <a href="" class="text-decoration-none">Sign in</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/components/post_card.html
<div class="card mx-auto mb-5" style="max-width: 32rem;">
    <div class="card-body p-0">
      <div class="card-title post__card__head d-flex justify-content-between px-3 pt-3">
          <div>
  
              <!-- Post Creator Profile Picture -->
              {% if post.user.picture %}
                  <img src="{{ post.user.picture.url }}" class="rounded-circle z-depth-0">
              {% else %}
                  <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png" class="rounded-circle z-depth-0">
              {% endif %}
              <!-- Post Creator Profile Picture End -->
  
              <span class="ml-2">
  
                  <!-- Link to Post Creator profile -->
                  <a href="{% url 'profile_view' post.user.username %}" class="text-decoration-none text-reset">{{ post.user.username }}</a>
                  <!-- Link to Post Creator profile End -->
  
              </span>
          </div>
          <div class="more__options__dot">
  
              <!-- Link to Open Posts Detail page -->
              <a class="text-reset text-decoration-none" type="button" href="{% url 'post_detail_view' post.pk %}">
                  <strong>Go to Post</strong>
              </a>
              <!-- Link to Open Posts Detail page End -->
  
          </div>
      </div>
      <div class="post__card__img">

templates/components/post_detail_card.html
<div class="card mx-auto mb-5">
    <div class="card-body p-0 row">
      <div class="col-12 col-md-8 pr-md-0">
          <div class="post__card__img">
  
              <!-- Post Image -->
              <img src="{{ post.image.url }}" style="width: 100%;">
  
          </div>
      </div>
      <div class="col-12 col-md-4 pl-md-0">
          <div class="card-title post__card__head d-flex justify-content-between px-3 pt-3">
              <div>
  
                  <!-- Post Creator Profile picture -->
                  {% if post.user.picture %}
                      <img src="{{ post.user.picture.url }}" class="rounded-circle z-depth-0">
                  {% else %}
                      <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png" class="rounded-circle z-depth-0">
                  {% endif %}
                  <!-- Post Creator Profile picture end -->
                  
                  <span class="ml-2">
  
                      <!-- Post creator username -->
                      <a href="{% url 'profile_view' post.user.username %}" class="text-decoration-none text-reset">{{ post.user.username }}</a>
  
                  </span>
              </div>
          </div>
          <div class="post__card__reactions d-flex justify-content-between py-3 px-3">
              <div class="d-flex">
                  <div class="post__like__btn ml-1 mr-2 row">
  
                      <!-- Like and Unlike Buttons -->
                      {% if liked_this_post %}
                          <form method="POST" action="{% url 'post_unlike_view' post.pk %}">
                              {% csrf_token %}
                              <button class="btn p-0 m-0" type="submit"><span class="fas fa-heart"></span></button>
                          </form>
                      {% else %}
                          <form method="POST" action="{% url 'post_like_view' post.pk %}">
                              {% csrf_token %}
                              <button class="btn p-0 m-0" type="submit"><span class="far fa-heart"></span></button>
                          </form>
                      {% endif %}
                      <!-- Like and Unlike Buttons End -->
  
                      <!-- Total likes count -->
                      <span class="mx-2">{{ post.likes_count }}</span>
  
                  </div>
                  <div class="post__comment__btn ml-1 mr-2 row">
                      <span class="far fa-comment"></span>
  
                      <!-- Total number of comments on post -->
                      <span class="mx-2">{{ post.comments_count }}</span>
  
                  </div>
              </div>
              <div>
                  <div class="post__save__btn">
  
                      <!-- Post Save Button -->
  
                      {% if not post_saved %}
                          <form method="POST" action="{% url 'post_save_view' post.pk %}">
                              {% csrf_token %}
                              <button class="btn p-0 m-0" type="submit">
                                  <span class="far fa-bookmark"></span>
                              </button>
                          </form>
                      {% else %}
                          <form method="POST" action="{% url 'post_unsave_view' post.pk %}">
                              {% csrf_token %}
                              <button class="btn p-0 m-0" type="submit">
                                  <span class="fas fa-bookmark"></span>
                              </button>
                          </form>
                      {% endif %}
                      <!-- Post Save Button end -->
  
                  </div>
              </div>
          </div>
  
          <!-- Post text if any -->
          {% if post.text %}
          <div class="post__card__text pt-3 px-2">
              <p>{{ post.text }}</p>
          </div>
          {% endif %}
  
          <div class="post__card__comments px-2 py-3 border-top border-bottom">
              <strong>Comments</strong>
          </div>
          <div class="overflow-auto">
  
              <!-- All the comments on this post -->
              {% for comment in post.comment_set.all %}
              <!-- Single Comment -->
              <div class="comment row py-3 px-4">
                  <a href="{% url 'profile_view' comment.user.username %}" class="text-reset text-decoration-none form-inline">
  
                      <!-- Commentor profile picture -->
                      {% if comment.user.picture %}
                      <img src="/media/{{ comment.user.picture }}" class="rounded-circle z-depth-0 profile__pic">
                      {% else %}
                      <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"  class="profile__pic rounded-circle z-depth-0">
                      {% endif %}
  
                      <!-- Commentor full name -->
                      <div class="my-auto ml-2">
                          <p class="m-0" style="font-size: 14px;">
                              {{ comment.user.full_name }}
                          </p>
                      </div>
  
                  </a>
                  <div class="w-100">
  
                      <!-- Comment text -->
                      <p class="m-0 text-wrap" style="font-size: 13px;">
                          {{ comment.text }}
                      </p>
  
                  </div>
              </div>
              <!-- Single Comment end -->
              {% endfor %}
              <!-- All the comments on this post end -->
  
          </div>
          <div class="w-100 my-3">
  
              <!-- Comment form -->
              <form class="form-inline justify-content-between mx-1" action="{% url 'post_comment_view' post.pk %}" method="POST">
                  {% csrf_token %}
                  <textarea name="comment_text" placeholder="Add a comment..." style="outline: none;border: 0" class="w-100"></textarea>
                  <button type="submit" class="btn btn-sm text-primary font-weight-bold">Post</button>
              </form>
              <!-- Comment form end -->
  
          </div>
      </div>
    </div>
  </div>